use dengue;

DROP PROCEDURE IF EXISTS obtener_informacion_paciente;
DELIMITER $$
CREATE PROCEDURE obtener_informacion_paciente(IN paciente_id INT)
BEGIN
  SELECT p.ID_REGISTRO, s.DESCRIPCION as SEXO, p.EDAD_ANOS,
		CASE WHEN p.HABLA_LENGUA_INDIG = 0 THEN 'No'
			 WHEN p.HABLA_LENGUA_INDIG = 1 THEN 'Si'
             END As HABLA_LENGUA_INDIG,
		CASE WHEN p.INDIGENA = 0 THEN 'No'
			 WHEN p.INDIGENA = 1 THEN 'Si'
             END As INDIGENA,
		p.FECHA_SIGN_SINTOMAS, tp.DESCRIPCION as TIPO_PACIENTE,
        CASE WHEN p.DEFUNCION = 0 THEN 'No'
			 WHEN p.DEFUNCION = 1 THEN 'Si'
             END As DEFUNCION,
		dic.DESCRIPCION as DICTAMEN,
        CASE WHEN p.TOMA_MUESTRA = 0 THEN 'No'
			 WHEN p.TOMA_MUESTRA = 1 THEN 'Si'
             End As TOMA_MUESTRA,
		pcr.DESCRIPCION as RESULTADO_PCR,
        caso.DESCRIPCION as ESTATUS_CASO,
		en.ENTIDAD_FEDERATIVA as ENTIDAD_UM_NOTIF,
        mu.MUNICIPIO as MUNICIPIO_UM_NOTIF,
        med.DESCRIPCION as INSTITUCION_UM_NOTIF,
        mu2.MUNICIPIO as ENTIDAD_RES,
        en2.ENTIDAD_FEDERATIVA as MUNICIPIO_RES,
        CASE WHEN a.HEMORRAGICOS = 0 THEN 'No'
			 WHEN a.HEMORRAGICOS = 1 THEN 'Si'
			 END As HEMORRAGICOS,
		CASE WHEN a.DIABETES = 0 THEN 'No'
			 WHEN a.DIABETES = 1 THEN 'Si'
			 END As DIABETES,
		CASE WHEN a.HIPERTENSION = 0 THEN 'No'
			 WHEN a.HIPERTENSION = 1 THEN 'Si'
			 END As HIPERTENSION,
		CASE WHEN a.ENFERMEDAD_ULC_PEPTICA = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_ULC_PEPTICA = 1 THEN 'Si'
			 END As ENFERMEDAD_ULC_PEPTICA,
		CASE WHEN a.ENFERMEDAD_RENAL = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_RENAL = 1 THEN 'Si'
			 END As ENFERMEDAD_RENAL,
		CASE WHEN a.INMUNOSUPR = 0 THEN 'No'
			 WHEN a.INMUNOSUPR = 1 THEN 'Si'
			 END As INMUNOSUPR,
		CASE WHEN a.CIRROSIS_HEPATICA = 0 THEN 'No'
			 WHEN a.CIRROSIS_HEPATICA = 1 THEN 'Si'
			 END As CIRROSIS_HEPATICA,
		CASE WHEN a.EMBARAZO = 0 THEN 'No'
			 WHEN a.EMBARAZO = 1 THEN 'Si'
			 END As EMBARAZO
  FROM paciente p
  JOIN um_notif un ON p.ID_REGISTRO = un.ID_REGISTRO
  JOIN lugar_residencia lr ON p.ID_REGISTRO = lr.ID_REGISTRO
  JOIN atributos_de_salud a ON p.ID_REGISTRO = a.ID_REGISTRO
  LEFT JOIN sexo s ON p.SEXO = s.CLAVE
  LEFT JOIN tipo_paciente as tp ON p.TIPO_PACIENTE = tp.CLAVE
  LEFT JOIN dictamen as dic ON p.DICTAMEN = dic.CLAVE
  LEFT JOIN resultados_pcr as pcr ON p.RESULTADO_PCR = pcr.CLAVE
  LEFT JOIN estatus_del_caso as caso ON p.ESTATUS_CASO = caso.CLAVE
  LEFT JOIN municipio as mu ON un.MUNICIPIO_UM_NOTIF = mu.CLAVE_MUNICIPIO AND un.ENTIDAD_UM_NOTIF = mu.CLAVE_ENTIDAD
  LEFT JOIN entidad as en ON un.ENTIDAD_UM_NOTIF = en.CLAVE_ENTIDAD
  LEFT JOIN institucion_medica as med ON un.INSTITUCION_UM_NOTIF = med.CLAVE
  LEFT JOIN municipio as mu2 ON lr.MUNICIPIO_RES = mu2.CLAVE_MUNICIPIO AND lr.ENTIDAD_RES = mu2.CLAVE_ENTIDAD
  LEFT JOIN entidad as en2 ON lr.ENTIDAD_RES = en2.CLAVE_ENTIDAD
  
  WHERE p.ID_REGISTRO = paciente_id;
END $$
DELIMITER ;

DROP PROCEDURE IF EXISTS obtener_informacion_entidad;
DELIMITER $$
CREATE PROCEDURE obtener_informacion_entidad(IN entidad_id INT, IN municipio_id INT)
BEGIN
  SELECT p.ID_REGISTRO, s.DESCRIPCION as SEXO, p.EDAD_ANOS,
		CASE WHEN p.HABLA_LENGUA_INDIG = 0 THEN 'No'
			 WHEN p.HABLA_LENGUA_INDIG = 1 THEN 'Si'
             END As HABLA_LENGUA_INDIG,
		CASE WHEN p.INDIGENA = 0 THEN 'No'
			 WHEN p.INDIGENA = 1 THEN 'Si'
             END As INDIGENA,
		p.FECHA_SIGN_SINTOMAS, tp.DESCRIPCION as TIPO_PACIENTE,
        CASE WHEN p.DEFUNCION = 0 THEN 'No'
			 WHEN p.DEFUNCION = 1 THEN 'Si'
             END As DEFUNCION,
		dic.DESCRIPCION as DICTAMEN,
        CASE WHEN p.TOMA_MUESTRA = 0 THEN 'No'
			 WHEN p.TOMA_MUESTRA = 1 THEN 'Si'
             End As TOMA_MUESTRA,
		pcr.DESCRIPCION as RESULTADO_PCR,
        caso.DESCRIPCION as ESTATUS_CASO,
		en.ENTIDAD_FEDERATIVA as ENTIDAD_UM_NOTIF,
        mu.MUNICIPIO as MUNICIPIO_UM_NOTIF,
        med.DESCRIPCION as INSTITUCION_UM_NOTIF,
        mu2.MUNICIPIO as ENTIDAD_RES,
        en2.ENTIDAD_FEDERATIVA as MUNICIPIO_RES,
        CASE WHEN a.HEMORRAGICOS = 0 THEN 'No'
			 WHEN a.HEMORRAGICOS = 1 THEN 'Si'
			 END As HEMORRAGICOS,
		CASE WHEN a.DIABETES = 0 THEN 'No'
			 WHEN a.DIABETES = 1 THEN 'Si'
			 END As DIABETES,
		CASE WHEN a.HIPERTENSION = 0 THEN 'No'
			 WHEN a.HIPERTENSION = 1 THEN 'Si'
			 END As HIPERTENSION,
		CASE WHEN a.ENFERMEDAD_ULC_PEPTICA = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_ULC_PEPTICA = 1 THEN 'Si'
			 END As ENFERMEDAD_ULC_PEPTICA,
		CASE WHEN a.ENFERMEDAD_RENAL = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_RENAL = 1 THEN 'Si'
			 END As ENFERMEDAD_RENAL,
		CASE WHEN a.INMUNOSUPR = 0 THEN 'No'
			 WHEN a.INMUNOSUPR = 1 THEN 'Si'
			 END As INMUNOSUPR,
		CASE WHEN a.CIRROSIS_HEPATICA = 0 THEN 'No'
			 WHEN a.CIRROSIS_HEPATICA = 1 THEN 'Si'
			 END As CIRROSIS_HEPATICA,
		CASE WHEN a.EMBARAZO = 0 THEN 'No'
			 WHEN a.EMBARAZO = 1 THEN 'Si'
			 END As EMBARAZO
  FROM paciente p
  JOIN um_notif un ON p.ID_REGISTRO = un.ID_REGISTRO
  JOIN lugar_residencia lr ON p.ID_REGISTRO = lr.ID_REGISTRO
  JOIN atributos_de_salud a ON p.ID_REGISTRO = a.ID_REGISTRO
  LEFT JOIN sexo s ON p.SEXO = s.CLAVE
  LEFT JOIN tipo_paciente as tp ON p.TIPO_PACIENTE = tp.CLAVE
  LEFT JOIN dictamen as dic ON p.DICTAMEN = dic.CLAVE
  LEFT JOIN resultados_pcr as pcr ON p.RESULTADO_PCR = pcr.CLAVE
  LEFT JOIN estatus_del_caso as caso ON p.ESTATUS_CASO = caso.CLAVE
  LEFT JOIN municipio as mu ON un.MUNICIPIO_UM_NOTIF = mu.CLAVE_MUNICIPIO AND un.ENTIDAD_UM_NOTIF = mu.CLAVE_ENTIDAD
  LEFT JOIN entidad as en ON un.ENTIDAD_UM_NOTIF = en.CLAVE_ENTIDAD
  LEFT JOIN institucion_medica as med ON un.INSTITUCION_UM_NOTIF = med.CLAVE
  LEFT JOIN municipio as mu2 ON lr.MUNICIPIO_RES = mu2.CLAVE_MUNICIPIO AND lr.ENTIDAD_RES = mu2.CLAVE_ENTIDAD
  LEFT JOIN entidad as en2 ON lr.ENTIDAD_RES = en2.CLAVE_ENTIDAD
  
  WHERE lr.ENTIDAD_RES = entidad_id AND lr.MUNICIPIO_RES = municipio_id;
END $$
DELIMITER ;

DROP PROCEDURE IF EXISTS MostrarRegistrosPorRangoEdad;
DELIMITER $$
CREATE PROCEDURE MostrarRegistrosPorRangoEdad(IN EdadMinima INT,IN EdadMaxima INT)
BEGIN
    SELECT p.ID_REGISTRO, s.DESCRIPCION as SEXO, p.EDAD_ANOS,
		CASE WHEN p.HABLA_LENGUA_INDIG = 0 THEN 'No'
			 WHEN p.HABLA_LENGUA_INDIG = 1 THEN 'Si'
             END As HABLA_LENGUA_INDIG,
		CASE WHEN p.INDIGENA = 0 THEN 'No'
			 WHEN p.INDIGENA = 1 THEN 'Si'
             END As INDIGENA,
		p.FECHA_SIGN_SINTOMAS, tp.DESCRIPCION as TIPO_PACIENTE,
        CASE WHEN p.DEFUNCION = 0 THEN 'No'
			 WHEN p.DEFUNCION = 1 THEN 'Si'
             END As DEFUNCION,
		dic.DESCRIPCION as DICTAMEN,
        CASE WHEN p.TOMA_MUESTRA = 0 THEN 'No'
			 WHEN p.TOMA_MUESTRA = 1 THEN 'Si'
             End As TOMA_MUESTRA,
		pcr.DESCRIPCION as RESULTADO_PCR,
        caso.DESCRIPCION as ESTATUS_CASO,
		en.ENTIDAD_FEDERATIVA as ENTIDAD_UM_NOTIF,
        mu.MUNICIPIO as MUNICIPIO_UM_NOTIF,
        med.DESCRIPCION as INSTITUCION_UM_NOTIF,
        mu2.MUNICIPIO as ENTIDAD_RES,
        en2.ENTIDAD_FEDERATIVA as MUNICIPIO_RES,
        CASE WHEN a.HEMORRAGICOS = 0 THEN 'No'
			 WHEN a.HEMORRAGICOS = 1 THEN 'Si'
			 END As HEMORRAGICOS,
		CASE WHEN a.DIABETES = 0 THEN 'No'
			 WHEN a.DIABETES = 1 THEN 'Si'
			 END As DIABETES,
		CASE WHEN a.HIPERTENSION = 0 THEN 'No'
			 WHEN a.HIPERTENSION = 1 THEN 'Si'
			 END As HIPERTENSION,
		CASE WHEN a.ENFERMEDAD_ULC_PEPTICA = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_ULC_PEPTICA = 1 THEN 'Si'
			 END As ENFERMEDAD_ULC_PEPTICA,
		CASE WHEN a.ENFERMEDAD_RENAL = 0 THEN 'No'
			 WHEN a.ENFERMEDAD_RENAL = 1 THEN 'Si'
			 END As ENFERMEDAD_RENAL,
		CASE WHEN a.INMUNOSUPR = 0 THEN 'No'
			 WHEN a.INMUNOSUPR = 1 THEN 'Si'
			 END As INMUNOSUPR,
		CASE WHEN a.CIRROSIS_HEPATICA = 0 THEN 'No'
			 WHEN a.CIRROSIS_HEPATICA = 1 THEN 'Si'
			 END As CIRROSIS_HEPATICA,
		CASE WHEN a.EMBARAZO = 0 THEN 'No'
			 WHEN a.EMBARAZO = 1 THEN 'Si'
			 END As EMBARAZO
  FROM paciente p
  JOIN um_notif un ON p.ID_REGISTRO = un.ID_REGISTRO
  JOIN lugar_residencia lr ON p.ID_REGISTRO = lr.ID_REGISTRO
  JOIN atributos_de_salud a ON p.ID_REGISTRO = a.ID_REGISTRO
  LEFT JOIN sexo s ON p.SEXO = s.CLAVE
  LEFT JOIN tipo_paciente as tp ON p.TIPO_PACIENTE = tp.CLAVE
  LEFT JOIN dictamen as dic ON p.DICTAMEN = dic.CLAVE
  LEFT JOIN resultados_pcr as pcr ON p.RESULTADO_PCR = pcr.CLAVE
  LEFT JOIN estatus_del_caso as caso ON p.ESTATUS_CASO = caso.CLAVE
  LEFT JOIN municipio as mu ON un.MUNICIPIO_UM_NOTIF = mu.CLAVE_MUNICIPIO AND un.ENTIDAD_UM_NOTIF = mu.CLAVE_ENTIDAD
  LEFT JOIN entidad as en ON un.ENTIDAD_UM_NOTIF = en.CLAVE_ENTIDAD
  LEFT JOIN institucion_medica as med ON un.INSTITUCION_UM_NOTIF = med.CLAVE
  LEFT JOIN municipio as mu2 ON lr.MUNICIPIO_RES = mu2.CLAVE_MUNICIPIO AND lr.ENTIDAD_RES = mu2.CLAVE_ENTIDAD
  LEFT JOIN entidad as en2 ON lr.ENTIDAD_RES = en2.CLAVE_ENTIDAD
    WHERE p.EDAD_ANOS BETWEEN EdadMinima AND EdadMaxima;
END $$
DELIMITER ;

DROP VIEW IF EXISTS porcentajes_entidad;
CREATE VIEW porcentajes_entidad AS
SELECT
    en.ENTIDAD_FEDERATIVA,
    COUNT(CASE WHEN p.HABLA_LENGUA_INDIG = 1 THEN 1 END) / COUNT(*) * 100 AS HABLA_INDIG,
    COUNT(CASE WHEN p.INDIGENA = 1 THEN 1 END) / COUNT(*) * 100 AS INDIG,
    COUNT(CASE WHEN p.DEFUNCION = 1 THEN 1 END) / COUNT(*) * 100 AS DEFUNCION,
    COUNT(CASE WHEN p.TOMA_MUESTRA = 1 THEN 1 END) / COUNT(*) * 100 AS TOMA_MUESTRA,
    COUNT(CASE WHEN a.HEMORRAGICOS = 1 THEN 1 END) / COUNT(*) * 100 AS HEMORRAGICOS,
    COUNT(CASE WHEN a.DIABETES = 1 THEN 1 END) / COUNT(*) * 100 AS DIABETES,
    COUNT(CASE WHEN a.HIPERTENSION = 1 THEN 1 END) / COUNT(*) * 100 AS HIPERTENSION,
    COUNT(CASE WHEN a.ENFERMEDAD_ULC_PEPTICA = 1 THEN 1 END) / COUNT(*) * 100 AS ENFERMEDAD_ULC_PEPTICA,
    COUNT(CASE WHEN a.ENFERMEDAD_RENAL = 1 THEN 1 END) / COUNT(*) * 100 AS ENFERMEDAD_RENAL,
    COUNT(CASE WHEN a.INMUNOSUPR = 1 THEN 1 END) / COUNT(*) * 100 AS INMUNOSUPR,
    COUNT(CASE WHEN a.CIRROSIS_HEPATICA = 1 THEN 1 END) / COUNT(*) * 100 AS CIRROSIS_HEPATICA,
    COUNT(CASE WHEN a.EMBARAZO = 1 THEN 1 END) / COUNT(*) * 100 AS EMBARAZO
FROM
    paciente p
    JOIN lugar_residencia lr ON p.ID_REGISTRO = lr.ID_REGISTRO
    JOIN atributos_de_salud a ON p.ID_REGISTRO = a.ID_REGISTRO
    JOIN entidad en ON lr.ENTIDAD_RES = en.CLAVE_ENTIDAD
WHERE
    lr.ENTIDAD_RES = entidad_res
GROUP BY
    en.ENTIDAD_FEDERATIVA;

DROP FUNCTION IF EXISTS ObtenerCasosDengue;
DELIMITER $$
CREATE FUNCTION ObtenerCasosDengue(
    entidad_federativa INT,
    municipio INT
) RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE total_casos INT;
    SELECT COUNT(*) INTO total_casos
	FROM
		paciente p
		JOIN lugar_residencia lr ON p.ID_REGISTRO = lr.ID_REGISTRO
		LEFT JOIN municipio as mu ON lr.MUNICIPIO_RES = mu.CLAVE_MUNICIPIO AND lr.ENTIDAD_RES = mu.CLAVE_ENTIDAD
		LEFT JOIN entidad as en ON lr.ENTIDAD_RES = en.CLAVE_ENTIDAD
        
    WHERE entidad_federativa = lr.ENTIDAD_RES AND municipio = mu.CLAVE_MUNICIPIO;
    RETURN total_casos;
END $$
DELIMITER ;


DROP FUNCTION IF EXISTS SintomaPrevalente;
DELIMITER $$
CREATE FUNCTION SintomaPrevalente(entidad VARCHAR(80)) RETURNS VARCHAR(80)
DETERMINISTIC
BEGIN
	DECLARE sintoma_prevalente varchar(50);
	SELECT CASE GREATEST(HEMORRAGICOS,
						 DIABETES,
                         HIPERTENSION,											
                         ENFERMEDAD_ULC_PEPTICA,
                         ENFERMEDAD_RENAL,
                         INMUNOSUPR,
                         CIRROSIS_HEPATICA,
                         EMBARAZO)
			WHEN HEMORRAGICOS THEN 'HEMORRAGICOS'
			WHEN DIABETES THEN 'DIABETES'
			WHEN HIPERTENSION THEN 'HIPERTENSION'
			WHEN ENFERMEDAD_ULC_PEPTICA THEN 'ENFERMEDAD_ULC_PEPTICA'
			WHEN ENFERMEDAD_RENAL THEN 'ENFERMEDAD_RENAL'
			WHEN INMUNOSUPR THEN 'INMUNOSUPR'
			WHEN CIRROSIS_HEPATICA THEN 'CIRROSIS_HEPATICA'
			WHEN EMBARAZO THEN 'EMBARAZO'
		END INTO sintoma_prevalente
	FROM
		porcentajes_entidad
	WHERE ENTIDAD_FEDERATIVA = entidad;
    RETURN sintoma_prevalente;
END $$
DELIMITER ;


USE dengue;